# -*- coding: utf-8 -*-
"""internshiptask4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cGxz37mVndDgAjU75vq4nUqInW6-2Y5I
"""

import pandas as pd
import matplotlib.pyplot as plt
from wordcloud import WordCloud

df = pd.read_csv("/content/twitter_training.csv", header=None)
df.columns = ["id", "entity", "sentiment", "tweet"]

df.dropna(inplace=True)

df["sentiment"].value_counts().plot(kind="bar")
plt.title("Sentiment Distribution")
plt.xlabel("Sentiment")
plt.ylabel("Number of Tweets")
plt.show()

df["entity"].value_counts().head(5).plot(kind="bar")
plt.title("Top 5 Entities")
plt.xlabel("Entity")
plt.ylabel("Tweet Count")
plt.show()


pd.crosstab(df["entity"], df["sentiment"]).head(5).plot(kind="bar", stacked=True)
plt.title("Entity-wise Sentiment")
plt.xlabel("Entity")
plt.ylabel("Tweet Count")
plt.show()


positive_text = " ".join(df[df["sentiment"] == "Positive"]["tweet"])

wordcloud = WordCloud(
    width=800,
    height=400,
    background_color="white"
).generate(positive_text)

plt.imshow(wordcloud)
plt.axis("off")
plt.title("Positive Tweets WordCloud")
plt.show()

